### ISSUE TITLE
print_matrix

### ISSUE THREAD

**Issue by yibrahimmoos** [D-F-D-P/MATREX#1]
the function should detect **the null pointer** and echos **"Null"** rather than crashing :grin: 
```
void matrix::print_matrix()
{
	for(int i=0;i<rows;i++){
		for(int j=0;j<columns;j++){
			cout<<elements[i][j]<<"\t";
		}
		cout<<endl;
	}
}
```

**Comment by YoussephAhmed** [comment]
good point :'D but I tried to to call print function from a matrix that is have ptr = NULL and it gave me a compilation error so i think we are safe

**Comment by yibrahimmoos** [comment]
do you even listen !?
