### ISSUE TITLE
Profiling using valgrind

### ISSUE THREAD

**Issue by WaleedEmadEzat** [D-F-D-P/MATREX#32]
@YoussephAhmed

**Comment by YoussephAhmed** [comment]
![valgrindmemcheck](https://user-images.githubusercontent.com/22798967/33782107-04cde52c-dc60-11e7-96ee-687ba934a68a.PNG)
looks like we got a problem here @YousifHmada xD

**Comment by YoussephAhmed** [comment]
![valgrind2](https://user-images.githubusercontent.com/22798967/33782766-9db74204-dc62-11e7-8f7c-eca22d255ea2.PNG)

**Comment by yibrahimmoos** [comment]
uhmmmmmmmmmm i'll see what i can do :smiley:

**Comment by YoussephAhmed** [comment]
![valgrindnew](https://user-images.githubusercontent.com/22798967/34828741-2a0eb248-f6e7-11e7-8f5b-acd48ce5cfbe.png)
Solved with this single line .

**Comment by yibrahimmoos** [comment]
good job :+1: :1st_place_medal:
